In [18]:
import pandas as pd

In [21]:
data = pd.read_csv("countyall.csv")
data['pop_dens'] = data["population_density_per_sq_mile"]

In [22]:
def categorize_hotspot(cases):
    if cases >= 50:
        return True
    else:
        return False

data['Hotspot'] = data['weeklyper100k'].apply(categorize_hotspot)

In [23]:
data.sort_values(by=['county', 'date'], inplace=True)

# Shift the 'Hotspot' column by 14 days to create a new column indicating hotspot status in two weeks
data['Hotspot_in_2_weeks'] = data.groupby('county')['Hotspot'].shift(-14)
data

,Unnamed: 0,date,county,state,fips,cases,deaths,Population,casesprop,deathsprop,...,dailydeath,weeklydeath,weeklyper100k,tranlevel,population_density_per_sq_mile,Minority_pct,region,pop_dens,Hotspot,Hotspot_in_2_weeks
0,0,2021-07-01,Alamance,North Carolina,37001.0,19035,289.0,175029.0,0.1088,0.0017,...,0.0,0.0,0.00,Low,404.8,0.3825,Northern,404.8,False,False
100,100,2021-07-02,Alamance,North Carolina,37001.0,19042,289.0,175029.0,0.1088,0.0017,...,0.0,0.0,0.00,Low,404.8,0.3825,Northern,404.8,False,False
200,200,2021-07-03,Alamance,North Carolina,37001.0,19042,289.0,175029.0,0.1088,0.0017,...,0.0,0.0,0.00,Low,404.8,0.3825,Northern,404.8,False,False
300,300,2021-07-04,Alamance,North Carolina,37001.0,19042,289.0,175029.0,0.1088,0.0017,...,0.0,0.0,0.00,Low,404.8,0.3825,Northern,404.8,False,False
400,400,2021-07-05,Alamance,North Carolina,37001.0,19042,289.0,175029.0,0.1088,0.0017,...,0.0,0.0,0.00,Low,404.8,0.3825,Northern,404.8,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15062,15099,2021-11-28,Yancey,North Carolina,37199.0,2996,35.0,18320.0,0.1635,0.0019,...,0.0,0.0,349.34,High,59.1,0.0868,Western,59.1,True,NaN
15162,15199,2021-11-29,Yancey,North Carolina,37199.0,3020,35.0,18320.0,0.1648,0.0019,...,0.0,0.0,245.63,High,59.1,0.0868,Western,59.1,True,NaN
15262,15299,2021-11-30,Yancey,North Carolina,37199.0,3024,35.0,18320.0,0.1651,0.0019,...,0.0,0.0,201.97,High,59.1,0.0868,Western,59.1,True,NaN
15361,15399,2021-12-01,Yancey,North Carolina,37199.0,3030,35.0,18320.0,0.1654,0.0019,...,0.0,0.0,185.59,High,59.1,0.0868,Western,59.1,True,NaN
15460,15499,2021-12-02,Yancey,North Carolina,37199.0,3050,35.0,18320.0,0.1665,0.0019,...,0.0,0.0,294.76,High,59.1,0.0868,Western,59.1,True,NaN

In [24]:
# choosing categories for analysis

data_analysis = data[["county", "date", "pop_dens", "Population", "cases",'weeklyper100k', "Hotspot"]]
data_analysis = data_analysis.loc[data_analysis['county'].isin(['Lincoln','Wake'])]
data_analysis

,county,date,pop_dens,Population,cases,weeklyper100k,Hotspot
54,Lincoln,2021-07-01,293.4,88742.0,10286,0.00,False
154,Lincoln,2021-07-02,293.4,88742.0,10289,0.00,False
254,Lincoln,2021-07-03,293.4,88742.0,10289,0.00,False
354,Lincoln,2021-07-04,293.4,88742.0,10289,0.00,False
454,Lincoln,2021-07-05,293.4,88742.0,10289,0.00,False
...,...,...,...,...,...,...,...
14854,Wake,2021-11-26,1353.3,1154170.0,135430,83.09,True
14954,Wake,2021-11-27,1353.3,1154170.0,135430,83.09,True
15054,Wake,2021-11-28,1353.3,1154170.0,135430,83.09,True
15154,Wake,2021-11-29,1353.3,1154170.0,136106,105.96,True
15254,Wake,2021-11-30,1353.3,1154170.0,136515,130.57,True

In [25]:
data_analysis.to_csv("analysis_data_small.csv")