In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("countyall.csv")

In [5]:
def categorize_hotspot(cases):
    if cases >= 50:
        return True
    else:
        return False

data['Hotspot'] = data['weeklyper100k'].apply(categorize_hotspot)

In [6]:
data.sort_values(by=['county', 'date'], inplace=True)

# Shift the 'Hotspot' column by 14 days to create a new column indicating hotspot status in two weeks
data['Hotspot_in_2_weeks'] = data.groupby('county')['Hotspot'].shift(-14)
data

,Unnamed: 0,date,county,state,fips,cases,deaths,Population,casesprop,deathsprop,dailycase,weeklycase,dailydeath,weeklydeath,weeklyper100k,tranlevel,Minority_pct,region,Hotspot,Hotspot_in_2_weeks
0,0,2021-07-01,Alamance,North Carolina,37001.0,19035,289.0,175029.0,0.1088,0.0017,0.0,0.0,0.0,0.0,0.00,Low,0.3825,Northern,False,False
100,100,2021-07-02,Alamance,North Carolina,37001.0,19042,289.0,175029.0,0.1088,0.0017,7.0,0.0,0.0,0.0,0.00,Low,0.3825,Northern,False,False
200,200,2021-07-03,Alamance,North Carolina,37001.0,19042,289.0,175029.0,0.1088,0.0017,0.0,0.0,0.0,0.0,0.00,Low,0.3825,Northern,False,False
300,300,2021-07-04,Alamance,North Carolina,37001.0,19042,289.0,175029.0,0.1088,0.0017,0.0,0.0,0.0,0.0,0.00,Low,0.3825,Northern,False,False
400,400,2021-07-05,Alamance,North Carolina,37001.0,19042,289.0,175029.0,0.1088,0.0017,0.0,0.0,0.0,0.0,0.00,Low,0.3825,Northern,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15062,15099,2021-11-28,Yancey,North Carolina,37199.0,2996,35.0,18320.0,0.1635,0.0019,0.0,64.0,0.0,0.0,349.34,High,0.0868,Western,True,NaN
15162,15199,2021-11-29,Yancey,North Carolina,37199.0,3020,35.0,18320.0,0.1648,0.0019,24.0,45.0,0.0,0.0,245.63,High,0.0868,Western,True,NaN
15262,15299,2021-11-30,Yancey,North Carolina,37199.0,3024,35.0,18320.0,0.1651,0.0019,4.0,37.0,0.0,0.0,201.97,High,0.0868,Western,True,NaN
15361,15399,2021-12-01,Yancey,North Carolina,37199.0,3030,35.0,18320.0,0.1654,0.0019,6.0,34.0,0.0,0.0,185.59,High,0.0868,Western,True,NaN
15460,15499,2021-12-02,Yancey,North Carolina,37199.0,3050,35.0,18320.0,0.1665,0.0019,20.0,54.0,0.0,0.0,294.76,High,0.0868,Western,True,NaN

In [15]:
# choosing categories for analysis

data_analysis = data[["date", "county", "Population", "cases", "Hotspot"]]
data_analysis = data_analysis.loc[data_analysis['county'].isin(['Lincoln','Gaston'])]
data_analysis

             date   county  Population  cases  Hotspot
35     2021-07-01   Gaston    233387.0  27187    False
135    2021-07-02   Gaston    233387.0  27198    False
235    2021-07-03   Gaston    233387.0  27198    False
335    2021-07-04   Gaston    233387.0  27198    False
435    2021-07-05   Gaston    233387.0  27198    False
...           ...      ...         ...    ...      ...
15017  2021-11-28  Lincoln     88742.0  15646     True
15117  2021-11-29  Lincoln     88742.0  15777     True
15217  2021-11-30  Lincoln     88742.0  15796     True
15317  2021-12-01  Lincoln     88742.0  15845     True
15416  2021-12-02  Lincoln     88742.0  15905     True

[310 rows x 5 columns]

In [16]:
data_analysis.to_csv("analysis_data_small.csv")